module.exports = [
  {
    "name" : "Jet Ski",
    "location": [25.2016428, 55.24525670000003],
    "city": "Jumeirah",
    "country": "Dubai",
    "address": "Jumeirah Beach, Dubai, UAE",
    "price": 450,
    "currency": "AED",
    "description": "This renowned water sport is one of the most popular & demanded water activity. Choose the discovery Tour and have fun by the Palm Jumeirah, take pictures in front of the Atlantis, enjoy the wonderful view of Jumeirah Beach Residence from the Sea on a Jetski. Fast, fun and sensation, enjoy the most exciting tour in Dubai with Sea Ride Dubai Jetski tour.",
    "tags": ["adventure", "water", "sport"],
    "begin_time": ["1.50 PM"],
    "end_time": "",
     "total_time": 30,
     "days": ["Su","Mo","Tu","We","Th","Fr"],
     "image": "dubai_jet_ski.jpg"
  },
  {
    "name" : "Helicopter Tour",
    "location": [25.2048493, 55.270782800000006],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Helipad, Dubai, UAE",
    "price": 535,
    "currency": "AED",
    "description": "Taking a helicopter tour of a city is a privilege that few get to enjoy. Our selection of thoughtfully designed aerial tours has been created to ensure an unforgettable experience for the whole family. From the internationally renowned Burj Khalifa and world famous Burj Al Arab to the spectacular The World and The Palm Jumeirah our aerial tours ensure a unique unobstructed view of Dubai.",
    "tags": ["adventure", "air", "tour"],
    "begin_time": ["9.00 AM", "12.00 PM", "3.00 PM", "6.00 PM"],
    "end_time": "",
     "total_time": 12,
     "days": ["Sa","Su","Mo","Tu","We","Th","Fr"],
     "image": "duba_helicopter_tour.jpg"
  },
  {
    "name" : "Dubai Aquarium & Underwater Zoo",
    "location": [25.196878, 55.27945049999994],
    "city": "Dubai",
    "country": "Dubai",
    "address": "The Dubai Mall, Downtown Dubai, UAE",
    "price": 100,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["water", "family", "adventure", "zoo"],
    "begin_time": ["10.00 AM", "11.00 AM", "12.00PM", "1.00PM", "2.00PM", "3.00PM","4.00PM","5.00PM","6.00 PM"],
    "end_time": "",
     "total_time": 120,
     "days": ["Sa","Su","Mo","Tu","We","Th","Fr"],
     "image": "dubai_underwater_zoo.jpg"
  },
  {
    "name" : "Dune Buggy & Arabian Night Expeience",
    "location": [25.2048493, 55.270782800000006],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Your Hotel, Dubi",
    "price": 595,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["desert", "sport", "adventure", "night"],
    "begin_time": ["2.30 PM"],
    "end_time": "",
     "total_time": 360,
     "days": ["Sa","Su","Mo","Tu","We","Th","Fr"],
     "image": "dubai-dune-buggy.jpg"
  },
  {
    "name" : "Dubai City Tour",
    "location": [25.197197, 55.27437639999994],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Your Hotel, Dubi",
    "price": 99,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["tour", "family"],
    "begin_time": ["9.00 PM"],
    "end_time": "",
     "total_time": 240,
     "days": ["Sa","Su","Mo","Tu","We","Th","Fr"],
     "image": "dubai_city_tour.jpg"
  },
  {
    "name" : "Dolphin & Seal Show",
    "location": [25.2346633, 55.32680210000001],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Dubai Dolphinarium, Dubi",
    "price": 100,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["tour", "family", "water"],
    "begin_time": ["11.00 AM"],
    "end_time": "",
     "total_time": 45,
     "days": ["Sa","Mo","Tu","We","Th","Fr"],
     "image": "dubai_dolphinarium.jpg"
  },
  {
    "name" : "Ferrari World & Yas Water World",
    "location": [24.4832389, 54.607439099999965],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Your Hotel, Dubi",
    "price": 405,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["tour", "family", "adventure"],
    "begin_time": ["9.00 AM"],
    "end_time": "",
     "total_time": 600,
     "days": ["Sa","Mo","Tu","We","Th","Fr"],
     "image": "dubai_ferrari_world.jpg"
  },
  {
    "name" : "Dinner in the Desert",
    "location": [24.4832389, 54.607439099999965],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Your Hotel, Dubi",
    "price": 150,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["tour", "family", "adventure", "desert","night"],
    "begin_time": ["4.30 PM"],
    "end_time": "",
     "total_time": 240,
     "days": ["Sa","Mo","Tu","We","Th","Fr"],
     "image": "dubai_dinner_desert.jpg"
  },
  {
    "name" : "Hummer Desert Safari",
    "location": [24.4832389, 54.607439099999965],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Your Hotel, Dubi",
    "price": 270,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["tour", "family", "adventure", "desert","night"],
    "begin_time": ["3.00 PM"],
    "end_time": "",
     "total_time": 360,
     "days": ["Sa","Mo","Tu","We","Th","Fr"],
     "image": "dubai_hummer.jpg"
  },
  {
    "name" : "Dubai Dibba Ride",
    "location": [25.27495249999999, 55.30437810000001],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Your Hotel, Dubi",
    "price": 350,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["tour", "family", "adventure", "water","cruise"],
    "begin_time": ["7.30 PM"],
    "end_time": "",
     "total_time": 600,
     "days": ["Sa","Mo","Tu","We","Th","Fr"],
     "image": "dubai_dibba_ride.jpg"
  },
  {
    "name" : "Rustar Cruise",
    "location": [25.27495249999999, 55.30437810000001],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Your Hotel, Dubi",
    "price": 280,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["tour", "family", "adventure", "water","cruise", "night"],
    "begin_time": ["9.00 PM"],
    "end_time": "",
     "total_time": 120,
     "days": ["Sa","Mo","Tu","We","Th","Fr"],
     "image": "dubai_rustar_cruise.jpg"
  },
  {
    "name" : "Dubai City Tour & Desert Safari",
    "location": [25.27495249999999, 55.30437810000001],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Your Hotel, Dubi",
    "price": 299,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["tour", "family", "adventure", "water","cruise", "night"],
    "begin_time": ["9.00 AM"],
    "end_time": "",
     "total_time": 660,
     "days": ["Sa","Mo","Tu","We","Th","Fr"],
     "image": "dubai_city_tour.jpg"
  },
  {
    "name" : "Marina & Palm Lagoon Boat Tour",
    "location": [25.27495249999999, 55.30437810000001],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Your Hotel, Dubi",
    "price": 150,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["tour", "family", "adventure", "water","cruise"],
    "begin_time": ["8.15 AM","6.00 PM", "7.00 PM"],
    "end_time": "",
     "total_time": 45,
     "days": ["Sa","Mo","Tu","We","Th","Fr"],
     "image": "dubai_lagoon.jpg"
  },
  {
    "name" : "Evening Desert Safari",
    "location": [25.27495249999999, 55.30437810000001],
    "city": "Dubai",
    "country": "Dubai",
    "address": "Your Hotel, Dubi",
    "price": 450,
    "currency": "AED",
    "description": "Enjoy 270 degree walthrough tunnel for incredible close encounters. The 10 million-litre tank at the Dubai Aquarium is one of the largest in the world, containing more than 33,000 aquatic animals and the largest collection of sand tiger sharks anywhere.  Rising to the third floor of The Dubai Mall, the aquarium is home to 140 species of sea life.",
    "tags": ["tour", "family", "adventure", "desert","safari", "night"],
    "begin_time": ["3.00 PM"],
    "end_time": "",
     "total_time": 360,
     "days": ["Sa","Mo","Tu","We","Th","Fr"],
     "image": "dubai_safari.jpg"
  }
]
